### ISSUE TITLE
Eh i uh gets um bannded for yours code??2!1

### ISSUE THREAD

**Issue by DemonDxv** [discord-trollering/Sparky-AntiCheat-Disabler#1]
Your disabler code no work?? It just autobahnd on the spankys network and it is fake nice clown men. So i decoded to buy beast cheet stitch.best for real small dollar and new I can fly all sponky with it shitty code skid 🤣

**Comment by FuXiiOn** [comment]
for real the code do not working?????????????????? I dont know why uploda fake code on tthis githubo.

**Comment by DemonDxv** [comment]
> for real the code do not working?????????????????? I dont know why uploda fake code on tthis githubo.

I noseessss write!

**Comment by Orialeng** [comment]
Why it don't not worker? I do can't understanding? Code do don't does nothing!!! It get me ban...whyyyy!!

**Comment by izimen** [comment]
I WAS BANNED FOREVER ON MY 5 YEARS OLD ACCOUNT!!! DISABLER DOESN'T WORK, LOST $100 RANK ACCOUNT!!! GIVE ME MY $100!!!!

**Comment by discord-trollering** [comment]
https://www.youtube.com/watch?v=NwnjXgoMe38 XD

**Comment by discord-trollering** [comment]
ya'll are quiet now? what is go on? i thought u enjoyed sucking off stitch devs?

**Comment by discord-trollering** [comment]
Damn, Things switched up real quick LOL

**Comment by discord-trollering** [comment]
https://www.youtube.com/watch?v=bHTG9-ghfjA

**Comment by discord-trollering** [comment]
Closing this. As It's another shitty attempt at covering up a backdoor 💀
